In [2]:
#Training phase
import numpy as np 
from sklearn import linear_model


# Import the data from the ".csv" Each file is about one deputy and contains the mean of the sentiment analysis 
# per day. The description of the function mean is above in the report.
mean_rubio=np.loadtxt(r'mean/mean_marcorubio.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_murphy=np.loadtxt(r'mean/mean_patrickMurphy.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_tammy=np.loadtxt(r'mean/mean_tammy.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_kirk=np.loadtxt(r'mean/mean_kirk.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_hassan=np.loadtxt(r'mean/mean_governorHassan.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_ayotte=np.loadtxt(r'mean/mean_kellyayotte.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_john=np.loadtxt(r'mean/mean_john.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_kirkpatrick=np.loadtxt(r'mean/mean_kirkpatrick.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_harris=np.loadtxt(r'mean/mean_harris.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_sanchez=np.loadtxt(r'mean/mean_sanchez.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_schumer=np.loadtxt(r'mean/mean_schumer.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_wendylong=np.loadtxt(r'mean/mean_wendylong.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_blumenthal=np.loadtxt(r'mean/mean_blumenthal.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_carter=np.loadtxt(r'mean/mean_carter.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_portman=np.loadtxt(r'mean/mean_portman.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_strickland=np.loadtxt(r'mean/mean_strickland.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_isakson=np.loadtxt(r'mean/mean_isakson.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_barksdale=np.loadtxt(r'mean/mean_barksdale.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_blunt=np.loadtxt(r'mean/mean_blunt.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_kander=np.loadtxt(r'mean/mean_kander.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_masto=np.loadtxt(r'mean/mean_catherineForNY.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_heck=np.loadtxt(r'mean/mean_heck.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_murray=np.loadtxt(r'mean/mean_pattyMurray.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_vance=np.loadtxt(r'mean/mean_chrisvance.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_moran=np.loadtxt(r'mean/mean_moran.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_wiesner=np.loadtxt(r'mean/mean_wiesner.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_crapo=np.loadtxt(r'mean/mean_crapo.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_sturgill=np.loadtxt(r'mean/mean_sturgill.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_young=np.loadtxt(r'mean/mean_ToddYoung.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_bayh=np.loadtxt(r'mean/mean_bayh.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_grassley=np.loadtxt(r'mean/mean_grassley.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_judge=np.loadtxt(r'mean/mean_pattyforIowa.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_paul=np.loadtxt(r'mean/mean_paul.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_gray=np.loadtxt(r'mean/mean_GrayLex.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_kennedy=np.loadtxt(r'mean/mean_kennedy.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_campbell=np.loadtxt(r'mean/mean_campbell.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

mean_hollen=np.loadtxt(r'mean/mean_vanhollen.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))
mean_szeliga=np.loadtxt(r'mean/mean_kathyForMD.csv', comments='++++',delimiter=';',skiprows=1,usecols=(4,))

# At this point, we want to add specif data to this list of mean. In this case, we had the number of follower that deputee has
# as well as the number of unique people that tweet about him during the period. The last one is the number of tweet about the deputee.
mean_rubio = np.append(mean_rubio,[1.8*1000000,27122, 73367])
mean_murphy = np.append(mean_murphy,[12.3*1000,5978, 21705])

mean_tammy = np.append(mean_tammy,[36.6*1000,2853, 4584])
mean_kirk = np.append(mean_kirk,[52.8*1000,4550, 6541])

mean_hassan = np.append(mean_hassan,[17.6*1000,672, 1296])
mean_ayotte = np.append(mean_ayotte,[58.8*1000,11043, 25570])

mean_john = np.append(mean_john,[2.09*1000000,21758, 40945])
mean_kirkpatrick = np.append(mean_kirkpatrick,[11.6*1000,534, 968])

mean_harris = np.append(mean_harris,[143*1000,3202, 5930])
mean_sanchez= np.append(mean_sanchez,[19.9*1000,885, 1333])

mean_schumer=np.append(mean_schumer,[207*1000,2759, 4961])
mean_wendylong=np.append(mean_wendylong,[7345,1007, 1872])

mean_blumenthal=np.append(mean_blumenthal,[48.2*100,915, 1572])
mean_carter=np.append(mean_carter,[1311,128, 320])

mean_portman=np.append(mean_portman,[59.7*100,1567, 3770])
mean_strickland=np.append(mean_strickland,[16700,2566, 6301])

mean_isakson=np.append(mean_isakson,[27600,834, 1626])
mean_barksdale=np.append(mean_barksdale,[1133,354, 1058])

mean_blunt=np.append(mean_blunt,[48.7*1000,1202, 2309])
mean_kander=np.append(mean_kander,[39.9*1000,2573,6148])

mean_masto=np.append(mean_masto,[16.2*1000,2145,6595])
mean_heck=np.append(mean_heck,[12.1*1000,1471, 2547])

mean_murray=np.append(mean_murray,[59.6*1000,1698,5063])
mean_vance=np.append(mean_vance,[1163,252,723])

mean_moran=np.append(mean_moran,[30.4*1000,484,771])
mean_wiesner=np.append(mean_wiesner,[48,13,23])

mean_crapo=np.append(mean_crapo,[26.8*1000,2111,3034])
mean_sturgill=np.append(mean_sturgill,[168,78,148])

mean_young=np.append(mean_young,[12.6*100,1088, 2959])
mean_bayh=np.append(mean_bayh,[3631,351,459])

mean_grassley=np.append(mean_grassley,[106*1000,2841,7644])
mean_judge=np.append(mean_judge,[1975,540,1596])

mean_paul=np.append(mean_paul,[1.04*1000000,13915, 26249])
mean_gray=np.append(mean_gray,[16.1*1000,306, 505])

mean_kennedy=np.append(mean_kennedy,[6133,259, 722])
mean_campbell=np.append(mean_campbell,[6456,231, 905])

mean_hollen=np.append(mean_hollen,[32.8*1000,518, 719])
mean_szeliga=np.append(mean_szeliga,[3556,411, 960])

In [38]:
# This is the list of result of the election. Every number represent the percentage of vote that the candidate obtain.
Y_all = [[52.0,44.3],
         [39.8, 54.9], 
         [47.87,47.97],
         [53.0,41.0],
         [38.2,61.8],
         [70.4,27.4],
         [34.6,63.2],
         [58.0,37.1], 
         [54.8,41.0],
         [46.2,49.3], 
         [44.7,47.1],
         [59.04,40.96],
         [32.2,62.1],
         [66.1,27.8 ],
         [42.2,52.1],
         [60.1,35.7],
         [42.73,57.27], 
         [39.35,60.65],
         [60.9,35.7]]

# This is the concatenation of all the data for the prediction. It contain the info about XX deputy.
MEANS_all = np.vstack((
        np.append(mean_rubio, mean_murphy),
        np.append(mean_tammy, mean_kirk),
        np.append(mean_ayotte, mean_hassan ),
        np.append(mean_john, mean_kirkpatrick),
        np.append(mean_sanchez, mean_harris ),
        np.append(mean_schumer, mean_wendylong),
        np.append(mean_carter, mean_blumenthal ),
        np.append(mean_portman, mean_strickland),
        np.append(mean_isakson, mean_barksdale),
        np.append(mean_kander, mean_blunt ), 
        np.append(mean_heck,mean_masto),
        np.append(mean_murray, mean_vance),
        np.append(mean_wiesner, mean_moran),
        np.append(mean_crapo, mean_sturgill),
        np.append(mean_bayh, mean_young),
        np.append(mean_grassley, mean_judge),
        np.append(mean_gray, mean_paul),
        np.append(mean_campbell, mean_kennedy ),
        np.append(mean_hollen, mean_szeliga)
    ))

Y_predict_final = np.zeros((4,2))
MEANS_predict_final = np.zeros((4,130))
for i in range(4):
    selected = np.random.randint(0,19-i, 1, dtype=int)
    Y_predict_final[i] = Y_all[selected]
    MEANS_predict_final[i] = MEANS_all[selected]
    
    MEANS_all = np.delete(MEANS_all, selected, 0)
    Y_all = np.delete(Y_all, selected, 0)
    
    
#print(Y_predict_final)

[[ 53.   41. ]
 [ 42.2  52.1]
 [ 46.2  49.3]
 [ 60.9  35.7]]


C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:49: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future


In [53]:
coef_all = np.zeros((2,130))
nbKeep = 0
for i in range(15):
    #Prediction phase - We create the prediction model
    clf = linear_model.LinearRegression(fit_intercept=False)
    
    MEANS_fit = np.delete(MEANS_all, i, 0)
    Y_fit = np.delete(Y_all, i, 0)

    # We fit the data of 18 deputy to the model and we keep 1 for the testing.
    clf.fit(MEANS_fit, Y_fit)
    
    #print (np.shape(clf.coef_))
    predIt = clf.predict(MEANS_all[i].reshape(1, -1))
    #print (predIt, '  to be : ', Y_all[i])
    
    #if (Y_all[i][0] > Y_all[i][1] and predIt[0][0] > predIt[0][1] ) or (Y_all[i][0] < Y_all[i][1] and predIt[0][0] < predIt[0][1]) :
        #print('yep')
        #nbKeep += 1
        #coef_all += clf.coef_
    #else :
        #print('nope')
        
#coef_all = coef_all/nbKeep

#print(coef_all)
    

[  0.00000000e+00   4.30686929e-01   3.73523909e-01   1.87456977e-01
   2.60091786e-01   2.52892447e-01   2.67828380e-01   3.46861355e-01
   1.44463411e-01   2.75875411e-01   1.20988089e-01   2.39671388e-01
   3.65043781e-01   1.49271963e-01   2.41113050e-01   2.59739422e-01
   2.90051366e-01   1.24391778e-01   2.15844197e-01   1.82446314e-01
  -1.13866796e-02   2.68248718e-01   2.58939868e-01  -9.67541673e-02
   2.76081101e-01   3.25674094e-01   1.78362622e-01   1.34043928e-01
   7.52848337e-02   9.74460738e-02   8.53602370e-02  -2.85293873e-01
   3.02087742e-01   4.58357898e-02   1.18672781e-01   1.86316497e-01
  -2.44765689e-01   2.65249168e-01   3.44147145e-01  -3.80507297e-02
   1.25599440e-02   1.10749695e-01   1.98948050e-01   3.19814312e-01
   0.00000000e+00   0.00000000e+00   0.00000000e+00   2.50000000e-01
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00

In [40]:
for i in range(len(Y_predict_final)):
    print (np.dot(MEANS_predict_final[i], clf.coef_[0]), ' and ', np.dot(MEANS_predict_final[i], clf.coef_[1])
           , 'to be ', Y_predict_final[i])

270.776966595  and  49.5449295207 to be  [ 53.  41.]
25.6144128535  and  26.9826951396 to be  [ 42.2  52.1]
24.205861014  and  33.1411875165 to be  [ 46.2  49.3]
51.4873278149  and  46.4079865703 to be  [ 60.9  35.7]


In [68]:
#Prediction phase - We create the prediction model
clf = linear_model.LinearRegression(fit_intercept=False)

# We fit the data of XXX deputy to the model and we keep XX for the testing.
clf.fit(MEANS_fit, Y_fit)
#print (clf.coef_)

#print (clf.predict(mean_portman))
#print (clf.predict(mean_wendylong))
for i in range(len(Y_predict)):
    #print(clf.score(MEANS_predict[i], Y_predict[i]))
    print (clf.predict(MEANS_predict[i]), '  to be : ', Y_predict[i])

[[  84.61081798  109.32656369]]   to be :  [39.8, 54.9]
[[ 72.78485148  68.48178408]]   to be :  [58.0, 37.1]
[[ 77.75062175  50.35209926]]   to be :  [44.7, 47.1]
[[ 31.41375646  24.05771587]]   to be :  [60.65, 39.35]


C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationW