In [4]:
import numpy as np
from sklearn import linear_model

In [5]:
#Example
b = np.array([3,5,7])
x = np.array([[1,6,9],  
              [2,7,7],   
              [3,4,5]])  
y = np.array([96,90,64])

x_test = np.array([[2,6,9],  
                  [2,7,6],   
                  [3,5,5]]) 

clf = linear_model.LinearRegression(fit_intercept=False)
clf.fit(x, y)
print (clf.coef_)
print (np.dot(x, clf.coef_))

print(clf.predict(x_test))

[ 3.  5.  7.]
[ 96.  90.  64.]
[ 99.  83.  69.]
